// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.devtools.responsive.metaViewport.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useXML", false);
user_pref("app.normandy.user_id", "515689fe-8df3-4682-ac7f-d07e0cfaa5e6");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1583928119);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1583928239);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1583934960);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1583987138);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1583927879);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1583927999);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1583927819);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1583928359);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 69663);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1583927714);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{30873689-2f6f-45e7-a0ff-39308c6bad23}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1583987126664");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1583988897664");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1583987128708");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1583990728708");
user_pref("browser.search.region", "KE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200117190643");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1583987119");
user_pref("browser.slowStartup.averageTime", 25149);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1583987114);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1583927782258");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "4e32bc5caee54095a3a01ff85c6549eb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 10 Mar 2020 21:23:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1583928122);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200117190643");
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e9337a44-4db2-4a48-9068-3901d7528d29\",\"formautofill@mozilla.org\":\"79f1ba93-6ecb-4782-a84c-9d067a0d3d15\",\"screenshots@mozilla.org\":\"79455349-dc36-4227-b691-8d15e16fddfe\",\"webcompat-reporter@mozilla.org\":\"e7b138ba-ec07-43ea-a61c-2ff713b8d72f\",\"webcompat@mozilla.org\":\"8a61a7af-0ff8-4796-98d7-39d81b862577\",\"default-theme@mozilla.org\":\"c4a3d6e6-eac8-42bc-a801-ec3190f69878\",\"google@search.mozilla.org\":\"ea90e676-e8ff-439b-ae4a-79812a28316a\",\"amazondotcom@search.mozilla.org\":\"5ccedeec-c509-462d-aa87-02fda6824657\",\"bing@search.mozilla.org\":\"39d15d0e-0810-4e4a-8d88-b66d0128b841\",\"ddg@search.mozilla.org\":\"ca4ea8cf-6886-478a-aea6-6947573db070\",\"ebay@search.mozilla.org\":\"bcd0446d-4a3b-4fed-8bfb-47e78859f956\",\"twitter@search.mozilla.org\":\"fa016318-191f-4e8a-92e9-a0145ef3c79b\",\"wikipedia@search.mozilla.org\":\"bd5aa2dc-2755-4c00-a4a8-9642d48b5bcb\"}");
user_pref("idle.lastDailyNotification", 1583928242);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1583927825);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200117190643");
user_pref("media.gmp-manager.lastCheck", 1583927807);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1583928242);
user_pref("places.history.expiration.transient_current_max_pages", 110283);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ec0e9805-222e-4661-852c-b0eb445edfd1");
user_pref("security.sandbox.plugin.tempDirSuffix", "7a4703f8-96a1-4043-a957-e3a83ad49835");
user_pref("services.blocklist.gfx.checked", 1583987123);
user_pref("services.blocklist.pinning.checked", 1583927838);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1583970742277\"");
user_pref("services.settings.last_update_seconds", 1583987123);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1583987123);
user_pref("services.settings.main.cfr-fxa.last_check", 1583987123);
user_pref("services.settings.main.cfr.last_check", 1583987123);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1583987123);
user_pref("services.settings.main.hijack-blocklists.last_check", 1583987123);
user_pref("services.settings.main.language-dictionaries.last_check", 1583987123);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1583987123);
user_pref("services.settings.main.public-suffix-list.last_check", 1583987123);
user_pref("services.settings.main.sites-classification.last_check", 1583987123);
user_pref("services.settings.main.tippytop.last_check", 1583987123);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1583987123);
user_pref("services.settings.main.whats-new-panel.last_check", 1583987123);
user_pref("services.settings.security.onecrl.checked", 1583927838);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1583928242);
user_pref("toolkit.startup.last_success", 1583987099);
user_pref("toolkit.telemetry.cachedClientID", "62000995-fa2e-4d52-b354-fd006c42a4f5");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
